apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nettools
  name: nettools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nettools
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nettools
    spec:
      containers:
      - image: cniketdkr/net-tools
        name: network-tools
        resources: {}
status: {}
